default: &default
  adapter: postgresql
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  database: <%= ENV['DB_ENV_POSTGRES_DATABASE'] %>
  username: <%= ENV['DB_ENV_POSTGRES_USERNAME'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  pool: <%= ENV['MAX_THREADS'] || 5 %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
